---

- hosts: all
  name: "WebServer Deployment Play"
  tasks:
  - name: Install Apache Packages 
    apt: name=apache2 state=present
    when: ansible_os_family=="Debian"

  - name: Start Apache Service
    service: name=apache2 state=started
    when: ansible_os_family=="Debian"

  - name: Install HTTPD Packages 
    yum: name=httpd state=present
    when: ansible_os_family=="RedHat"

  - name: Start HTTPD Service
    service: name=httpd state=started
    when: ansible_os_family=="RedHat"

  - name: Custom Web Page Deployment
    copy: src=files/index.html dest=/var/www/html/index.html

  - name: Download Mario Image 
    get_url: url="https://www.mariomayhem.com/downloads/wallpapers/7/nsmb_wp7_1280.jpg" dest=/var/www/html/mario.jpg mode=0755

  - name: Custom Info Page Deployment
    template: src=templates/info.j2 dest=/var/www/html/info.html

- hosts: 'web:db'
  name: "Git Deployment Play"
  tasks:
  - name: Install git Packages 
    apt: name=git state=present

